<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.10.2" name="ooo32" tilewidth="32" tileheight="32" tilecount="72" columns="8">
 <image source="tileset_32x32.png" width="256" height="288"/>
 <tile id="0"><properties><property name="name" value="grass_left"/><property name="type" value="solid"/></properties></tile>
 <tile id="1"><properties><property name="name" value="grass_mid"/><property name="type" value="solid"/></properties></tile>
 <tile id="2"><properties><property name="name" value="grass_right"/><property name="type" value="solid"/></properties></tile>
 <tile id="3"><properties><property name="name" value="grass_single"/><property name="type" value="solid"/></properties></tile>
 <tile id="4"><properties><property name="name" value="dirt_left"/><property name="type" value="solid"/></properties></tile>
 <tile id="5"><properties><property name="name" value="dirt_mid"/><property name="type" value="solid"/></properties></tile>
 <tile id="6"><properties><property name="name" value="dirt_right"/><property name="type" value="solid"/></properties></tile>
 <tile id="7"><properties><property name="name" value="dirt_bottom"/><property name="type" value="solid"/></properties></tile>
 <tile id="8"><properties><property name="name" value="plat_left"/><property name="type" value="oneway"/></properties></tile>
 <tile id="9"><properties><property name="name" value="plat_mid"/><property name="type" value="oneway"/></properties></tile>
 <tile id="10"><properties><property name="name" value="plat_right"/><property name="type" value="oneway"/></properties></tile>
 <tile id="11"><properties><property name="name" value="blk_brick"/><property name="type" value="solid"/></properties></tile>
 <tile id="12"><properties><property name="name" value="blk_gum"/><property name="type" value="solid"/></properties></tile>
 <tile id="13"><properties><property name="name" value="blk_ice"/><property name="type" value="slippery"/></properties></tile>
 <tile id="14"><properties><property name="name" value="blk_cracked"/><property name="type" value="breakable"/></properties></tile>
 <tile id="15"><properties><property name="name" value="blk_choco"/><property name="type" value="solid"/></properties></tile>
 <tile id="16"><properties><property name="name" value="spikes_up"/><property name="type" value="hazard"/></properties></tile>
 <tile id="17"><properties><property name="name" value="spikes_down"/><property name="type" value="hazard"/></properties></tile>
 <tile id="18"><properties><property name="name" value="thorns"/><property name="type" value="hazard"/></properties></tile>
 <tile id="19"><properties><property name="name" value="saw"/><property name="type" value="hazard"/></properties></tile>
 <tile id="20"><properties><property name="name" value="slime_top"/><property name="type" value="hazard"/></properties></tile>
 <tile id="21"><properties><property name="name" value="slime_body"/><property name="type" value="hazard"/></properties></tile>
 <tile id="22"><properties><property name="name" value="goo_top"/><property name="type" value="hazard"/></properties></tile>
 <tile id="23"><properties><property name="name" value="goo_body"/><property name="type" value="hazard"/></properties></tile>
 <tile id="24"><properties><property name="name" value="qblock"/><property name="type" value="bonus"/></properties></tile>
 <tile id="25"><properties><property name="name" value="coin"/><property name="type" value="pickup"/></properties></tile>
 <tile id="26"><properties><property name="name" value="spring"/><property name="type" value="bounce"/></properties></tile>
 <tile id="27"><properties><property name="name" value="checkpoint_top"/><property name="type" value="checkpoint"/></properties></tile>
 <tile id="28"><properties><property name="name" value="checkpoint_pole"/><property name="type" value="checkpoint"/></properties></tile>
 <tile id="29"><properties><property name="name" value="checkpoint_base"/><property name="type" value="checkpoint"/></properties></tile>
 <tile id="30"><properties><property name="name" value="door"/><property name="type" value="exit"/></properties></tile>
 <tile id="31"><properties><property name="name" value="ladder"/><property name="type" value="climb"/></properties></tile>
 <tile id="32"><properties><property name="name" value="grave"/><property name="type" value="corpse"/></properties></tile>
 <tile id="33"><properties><property name="name" value="bones"/><property name="type" value="corpse"/></properties></tile>
 <tile id="34"><properties><property name="name" value="torch"/><property name="type" value="deco"/></properties></tile>
 <tile id="35"><properties><property name="name" value="crystal"/><property name="type" value="deco"/></properties></tile>
 <tile id="36"><properties><property name="name" value="mushroom_sm"/><property name="type" value="deco"/></properties></tile>
 <tile id="37"><properties><property name="name" value="mushroom_lg"/><property name="type" value="deco"/></properties></tile>
 <tile id="38"><properties><property name="name" value="flower"/><property name="type" value="deco"/></properties></tile>
 <tile id="39"><properties><property name="name" value="grass_tuft"/><property name="type" value="deco"/></properties></tile>
 <tile id="40"><properties><property name="name" value="cloud_left"/><property name="type" value="bg"/></properties></tile>
 <tile id="41"><properties><property name="name" value="cloud_mid"/><property name="type" value="bg"/></properties></tile>
 <tile id="42"><properties><property name="name" value="cloud_right"/><property name="type" value="bg"/></properties></tile>
 <tile id="43"><properties><property name="name" value="hill"/><property name="type" value="bg"/></properties></tile>
 <tile id="44"><properties><property name="name" value="trunk"/><property name="type" value="bg"/></properties></tile>
 <tile id="45"><properties><property name="name" value="canopy"/><property name="type" value="bg"/></properties></tile>
 <tile id="46"><properties><property name="name" value="star"/><property name="type" value="deco"/></properties></tile>
 <tile id="47"><properties><property name="name" value="stepping_stones"/><property name="type" value="deco"/></properties></tile>
 <tile id="48"><properties><property name="name" value="grassrock_left"/><property name="type" value="solid"/></properties></tile>
 <tile id="49"><properties><property name="name" value="grassrock_mid"/><property name="type" value="solid"/></properties></tile>
 <tile id="50"><properties><property name="name" value="grassrock_right"/><property name="type" value="solid"/></properties></tile>
 <tile id="51"><properties><property name="name" value="grassrock_single"/><property name="type" value="solid"/></properties></tile>
 <tile id="52"><properties><property name="name" value="rock_left"/><property name="type" value="solid"/></properties></tile>
 <tile id="53"><properties><property name="name" value="rock_mid"/><property name="type" value="solid"/></properties></tile>
 <tile id="54"><properties><property name="name" value="rock_right"/><property name="type" value="solid"/></properties></tile>
 <tile id="55"><properties><property name="name" value="rock_bottom"/><property name="type" value="solid"/></properties></tile>
 <tile id="56"><properties><property name="name" value="path_left"/><property name="type" value="solid"/></properties></tile>
 <tile id="57"><properties><property name="name" value="path_mid"/><property name="type" value="solid"/></properties></tile>
 <tile id="58"><properties><property name="name" value="path_right"/><property name="type" value="solid"/></properties></tile>
 <tile id="59"><properties><property name="name" value="path_single"/><property name="type" value="solid"/></properties></tile>
 <tile id="60"><properties><property name="name" value="masonry_left"/><property name="type" value="solid"/></properties></tile>
 <tile id="61"><properties><property name="name" value="masonry_mid"/><property name="type" value="solid"/></properties></tile>
 <tile id="62"><properties><property name="name" value="masonry_right"/><property name="type" value="solid"/></properties></tile>
 <tile id="63"><properties><property name="name" value="path_slab"/><property name="type" value="oneway"/></properties></tile>
 <tile id="64"><properties><property name="name" value="rock_mid_b"/><property name="type" value="solid"/></properties></tile>
 <tile id="65"><properties><property name="name" value="rock_mid_c"/><property name="type" value="solid"/></properties></tile>
 <tile id="66"><properties><property name="name" value="grassrock_mid_b"/><property name="type" value="solid"/></properties></tile>
 <tile id="67"><properties><property name="name" value="grassrock_mid_c"/><property name="type" value="solid"/></properties></tile>
 <tile id="68"><properties><property name="name" value="rock_bottom_b"/><property name="type" value="solid"/></properties></tile>
 <tile id="69"><properties><property name="name" value="path_mid_b"/><property name="type" value="solid"/></properties></tile>
 <tile id="70"><properties><property name="name" value="path_mid_c"/><property name="type" value="solid"/></properties></tile>
 <tile id="71"><properties><property name="name" value="grass_mid_b"/><property name="type" value="solid"/></properties></tile>
</tileset>